targets:
  $default:
    builders:
      json_serializable:
        options:
          include_if_null: false
          explicit_to_json: true
      freezed:
        options:
          union_key: type
          union_value_case: pascal
          generic_argument_factories: true